// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SftpXmlTask.DataAccess.XmlDataAccessImplementation.Models;

public partial class PurchaseOrderCustomer
{
    public int PurchaseOrderCustomerId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Oib { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpd { get; set; }

    public string LastUpdBy { get; set; }

    public string LastUpdApp { get; set; }

    public int PurchaseOrderId { get; set; }
}