// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SftpXmlTask.DataAccess.XmlDataAccessImplementation.Models;

public partial class PurchaseOrderItem
{
    public int PurchaseOrderItemId { get; set; }

    public string ProductName { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpd { get; set; }

    public string LastUpdBy { get; set; }

    public string LastUpdApp { get; set; }

    public int PurchaseOrderId { get; set; }
}